/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package telkomtalk.UI.pkg;

import java.awt.Point;
import java.io.File;
import java.io.FileFilter;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author AhmadFauzi__
 */
public class RegisterUI extends javax.swing.JFrame {
    Point point = new Point();
    /**
     * Creates new form RegisterUI
     */
    public RegisterUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JLabel();
        registerButton2 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        retypeField = new javax.swing.JPasswordField();
        avatar = new javax.swing.JLabel();
        uploadButton = new javax.swing.JLabel();
        bakcground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(360, 592));
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telkomtalk/UI/images/close_default.png"))); // NOI18N
        closeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeButtonMouseReleased(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 3, 20, 20));

        minimizeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telkomtalk/UI/images/minimize_default.png"))); // NOI18N
        minimizeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizeButtonMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseReleased(evt);
            }
        });
        getContentPane().add(minimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 3, 20, 20));

        registerButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telkomtalk/UI/images/button_register_default_2.png"))); // NOI18N
        registerButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerButton2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerButton2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                registerButton2MouseReleased(evt);
            }
        });
        getContentPane().add(registerButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 540, 110, 40));

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telkomtalk/UI/images/button_cancel_default.png"))); // NOI18N
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelButtonMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelButtonMouseReleased(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 110, 40));

        usernameField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        usernameField.setBorder(null);
        usernameField.setMinimumSize(new java.awt.Dimension(20, 240));
        usernameField.setPreferredSize(new java.awt.Dimension(20, 240));
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 135, 230, 25));

        emailField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        emailField.setBorder(null);
        emailField.setMinimumSize(new java.awt.Dimension(20, 240));
        emailField.setPreferredSize(new java.awt.Dimension(20, 240));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 220, 230, 25));

        passField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passField.setBorder(null);
        passField.setMinimumSize(new java.awt.Dimension(230, 25));
        passField.setPreferredSize(new java.awt.Dimension(230, 25));
        getContentPane().add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 301, 230, 25));

        retypeField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        retypeField.setBorder(null);
        retypeField.setMinimumSize(new java.awt.Dimension(230, 25));
        retypeField.setPreferredSize(new java.awt.Dimension(230, 25));
        getContentPane().add(retypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 390, 230, 25));

        avatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatar.setText("avatar");
        avatar.setMaximumSize(new java.awt.Dimension(58, 58));
        avatar.setMinimumSize(new java.awt.Dimension(58, 58));
        avatar.setPreferredSize(new java.awt.Dimension(58, 58));
        getContentPane().add(avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 450, -1, -1));

        uploadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telkomtalk/UI/images/button_upload_default.png"))); // NOI18N
        uploadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uploadButton.setMaximumSize(new java.awt.Dimension(109, 25));
        uploadButton.setMinimumSize(new java.awt.Dimension(109, 25));
        uploadButton.setPreferredSize(new java.awt.Dimension(109, 25));
        uploadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                uploadButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                uploadButtonMouseReleased(evt);
            }
        });
        getContentPane().add(uploadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        bakcground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telkomtalk/UI/images/RegisterUI.png"))); // NOI18N
        getContentPane().add(bakcground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 592));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = getLocation();
        setLocation(p.x+evt.getX()-point.x,p.y+evt.getY()-point.y);
    }//GEN-LAST:event_formMouseDragged

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered
        ImageIcon closeImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/close_hover.png"));
        closeButton.setIcon(closeImage);
    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMousePressed
        ImageIcon closeImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/close_pressed.png"));
        closeButton.setIcon(closeImage);
    }//GEN-LAST:event_closeButtonMousePressed

    private void closeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseExited
        ImageIcon closeImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/close_default.png"));
        closeButton.setIcon(closeImage);
    }//GEN-LAST:event_closeButtonMouseExited

    private void closeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseReleased
        ImageIcon closeImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/close_default.png"));
        closeButton.setIcon(closeImage);

        hide();
    }//GEN-LAST:event_closeButtonMouseReleased

    private void minimizeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseEntered
        ImageIcon minimizeImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/minimize_hover.png"));
        minimizeButton.setIcon(minimizeImage);
    }//GEN-LAST:event_minimizeButtonMouseEntered

    private void minimizeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMousePressed
        ImageIcon minimizeImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/minimize_pressed.png"));
        minimizeButton.setIcon(minimizeImage);
    }//GEN-LAST:event_minimizeButtonMousePressed

    private void minimizeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseExited
        ImageIcon minimizeImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/minimize_default.png"));
        minimizeButton.setIcon(minimizeImage);
    }//GEN-LAST:event_minimizeButtonMouseExited

    private void minimizeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseReleased
        ImageIcon minimizeImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/minimize_default.png"));
        minimizeButton.setIcon(minimizeImage);

        setExtendedState(getExtendedState()| LoginUI.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonMouseReleased

    private void registerButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButton2MouseEntered
        ImageIcon registerImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/button_register_hover_2.png"));
        registerButton2.setIcon(registerImage);
    }//GEN-LAST:event_registerButton2MouseEntered

    private void registerButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButton2MouseExited
        ImageIcon registerImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/button_register_default_2.png"));
        registerButton2.setIcon(registerImage);
    }//GEN-LAST:event_registerButton2MouseExited

    private void registerButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButton2MousePressed
        ImageIcon registerImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/button_register_pressed_2.png"));
        registerButton2.setIcon(registerImage);
    }//GEN-LAST:event_registerButton2MousePressed

    private void registerButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButton2MouseReleased
        ImageIcon registerImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/button_register_default_2.png"));
        registerButton2.setIcon(registerImage);
    }//GEN-LAST:event_registerButton2MouseReleased

    private void cancelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseEntered
        ImageIcon cancelImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/button_cancel_hover.png"));
        cancelButton.setIcon(cancelImage);
    }//GEN-LAST:event_cancelButtonMouseEntered

    private void cancelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseExited
        ImageIcon cancelImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/button_cancel_default.png"));
        cancelButton.setIcon(cancelImage);
    }//GEN-LAST:event_cancelButtonMouseExited

    private void cancelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMousePressed
        ImageIcon cancelImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/button_cancel_pressed.png"));
        cancelButton.setIcon(cancelImage);
    }//GEN-LAST:event_cancelButtonMousePressed

    private void cancelButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseReleased
        ImageIcon cancelImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/button_cancel_default.png"));
        cancelButton.setIcon(cancelImage);
        
        hide();
    }//GEN-LAST:event_cancelButtonMouseReleased

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        
    }//GEN-LAST:event_emailFieldActionPerformed

    private void uploadButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadButtonMousePressed
        ImageIcon uploadImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/button_upload_pressed.png"));
        uploadButton.setIcon(uploadImage);
    }//GEN-LAST:event_uploadButtonMousePressed

    private void uploadButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadButtonMouseReleased
        ImageIcon uploadImage = new ImageIcon(getClass().getResource("/telkomtalk/UI/images/button_upload_default.png"));
        uploadButton.setIcon(uploadImage);
        
        //================================================================================================================
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image","jpg","png");
        
        JFileChooser chooser = new JFileChooser();
        
        chooser.addChoosableFileFilter(filter);
        
        int returnVal = chooser.showOpenDialog(null);
        
        if(returnVal == JFileChooser.APPROVE_OPTION ){
            File myFile = chooser.getSelectedFile();
            String text = myFile + "";
        }
    }//GEN-LAST:event_uploadButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar;
    private javax.swing.JLabel bakcground;
    private javax.swing.JLabel cancelButton;
    private javax.swing.JLabel closeButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel registerButton2;
    private javax.swing.JPasswordField retypeField;
    private javax.swing.JLabel uploadButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
